name: Publish Release

on:
  push:
    branches:
      - main

jobs:
  check-bats-version:
    runs-on: ubuntu-latest

    env:
      CLASPRC_ACCESS_TOKEN: ${{ secrets.CLASPRC_ACCESS_TOKEN }}
      CLASPRC_CLIENT_ID: ${{ secrets.CLASPRC_CLIENT_ID }}
      CLASPRC_CLIENT_SECRET: ${{ secrets.CLASPRC_CLIENT_SECRET }}
      CLASPRC_EXPIRY_DATE: ${{ secrets.CLASPRC_EXPIRY_DATE }}
      CLASPRC_ID_TOKEN: ${{ secrets.CLASPRC_ID_TOKEN }}
      CLASPRC_REFRESH_TOKEN: ${{ secrets.CLASPRC_REFRESH_TOKEN }}
      TZ: 'Asia/Tokyo' # タイムゾーン指定

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Clasp
        run: |
          npm init -y
          npm install clasp -g
      - name: Create ~/.clasprc.json
        run: |
          echo $(cat <<-EOS
          {
            "token": {
              "access_token": "${CLASPRC_ACCESS_TOKEN}",
              "scope": "https://www.googleapis.com/auth/script.deployments https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/drive.file openid https://www.googleapis.com/auth/service.management https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/drive.metadata.readonly https://www.googleapis.com/auth/logging.read https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/script.webapp.deploy",
              "token_type": "Bearer",
              "id_token": "${CLASPRC_ID_TOKEN}",
              "expiry_date": ${CLASPRC_EXPIRY_DATE},
              "refresh_token": "${CLASPRC_REFRESH_TOKEN}"
            },
            "oauth2ClientSettings": {
              "clientId": "${CLASPRC_CLIENT_ID}",
              "clientSecret": "${CLASPRC_CLIENT_SECRET}",
              "redirectUri": "http://localhost"
            },
            "isLocalCreds": false
          }
          EOS
          ) > ~/.clasprc.json

      - name: Get current datetime
        id: get_current_datetime
        run: echo ::set-output name=CURRENT_DATETIME::$(date +'%Y-%m-%d %H:%M:%S')

      - name: Upload files in study
        run: |
          cd qa_process/study
          npx @google/clasp push --force

      - name: Add version
        run: npx @google/clasp version ${{ steps.get_current_datetime.outputs.CURRENT_DATETIME }}
